# Generated by Django 5.2.14 on 2026-05-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACKED', 'Acked'), ('expired', 'Expired')], default='PENDING', max_length=10),
        ),
    ]
