# Generated by Django 5.2.14 on 2026-05-09 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_command_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
